use std::error::Error;
mod hacker_news;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    todo!()
}
